begin;

create table if not exists public.ai_feedback_events (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  request_id text not null default '',
  feature text not null,
  rating text not null check (rating in ('helpful', 'not_helpful')),
  reason_codes text[] not null default '{}',
  comment text not null default '',
  user_id uuid,
  anon_id text not null default '',
  session_id text not null default '',
  entity_type text not null default '',
  entity_id text not null default ''
);

create index if not exists ai_feedback_events_request_idx
  on public.ai_feedback_events (request_id);

create index if not exists ai_feedback_events_feature_created_idx
  on public.ai_feedback_events (feature, created_at desc);

alter table public.ai_feedback_events enable row level security;

drop policy if exists ai_feedback_events_read on public.ai_feedback_events;
revoke all on table public.ai_feedback_events from anon, authenticated;

commit;
