begin;

create table if not exists public.ai_usage_logs (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  mode text not null check (mode in ('free', 'paid')),
  endpoint text not null,
  outcome text not null check (outcome in ('success', 'irrelevant', 'rate_limited', 'error')),
  serial text,
  user_id uuid,
  model text
);

create index if not exists ai_usage_logs_created_at_idx
  on public.ai_usage_logs (created_at desc);

create index if not exists ai_usage_logs_mode_created_at_idx
  on public.ai_usage_logs (mode, created_at desc);

create index if not exists ai_usage_logs_endpoint_created_at_idx
  on public.ai_usage_logs (endpoint, created_at desc);

alter table public.ai_usage_logs enable row level security;

commit;
