begin;

create table if not exists public.analytics_events (
  id bigint generated by default as identity primary key,
  occurred_at timestamptz not null default now(),
  event_name text not null,
  event_version smallint not null default 1,
  session_id text not null default '',
  anon_id text not null default '',
  user_id uuid,
  role text not null default '',
  page text not null default '',
  surface text not null default '',
  entity_type text not null default '',
  entity_id text not null default '',
  request_id text not null default '',
  props jsonb not null default '{}'::jsonb
);

create index if not exists analytics_events_occurred_idx
  on public.analytics_events (occurred_at desc);

create index if not exists analytics_events_name_occurred_idx
  on public.analytics_events (event_name, occurred_at desc);

create index if not exists analytics_events_user_occurred_idx
  on public.analytics_events (user_id, occurred_at desc);

create index if not exists analytics_events_entity_idx
  on public.analytics_events (entity_type, entity_id, occurred_at desc);

create index if not exists analytics_events_props_gin
  on public.analytics_events using gin (props);

alter table public.analytics_events enable row level security;

drop policy if exists analytics_events_read on public.analytics_events;
revoke all on table public.analytics_events from anon, authenticated;

commit;
