-- Public question totals are aggregated in PostgreSQL, without transferring raw
-- answer logs through PostgREST row limits. Also supplies the base table on new installs.
begin;

do $$
begin
  if to_regclass('public.answers') is null then
    create table public.answers (
      id bigint generated by default as identity primary key,
      serial text not null,
      is_correct boolean not null,
      selected_index integer,
      anon_id text,
      created_at timestamptz not null default now()
    );
    alter table public.answers enable row level security;
    grant insert on public.answers to anon, authenticated;
    grant usage on sequence public.answers_id_seq to anon, authenticated;
    create policy answers_guest_insert on public.answers for insert to anon, authenticated with check (true);
  end if;
end $$;

create index if not exists answers_serial_created_idx on public.answers(serial, created_at desc);

create or replace function public.worker_answer_stats(p_serials text[])
returns jsonb language plpgsql security definer set search_path = '' as $$
declare result jsonb;
begin
  if p_serials is null or cardinality(p_serials) not between 1 and 200 then
    raise exception 'Expected 1 to 200 serials' using errcode = '22023';
  end if;
  -- Preserve the UI's existing measure: the latest answer per anonymous actor
  -- and UTC calendar day, rather than every retry. Null dates form one group.
  with requested as (select distinct unnest(p_serials) as serial),
  latest as (
    select distinct on (a.serial, coalesce(a.anon_id, ''), (a.created_at at time zone 'UTC')::date)
      a.serial, a.is_correct
    from public.answers a join requested r on r.serial = a.serial
    order by a.serial, coalesce(a.anon_id, ''), (a.created_at at time zone 'UTC')::date,
      a.created_at desc nulls last, a.is_correct desc
  ), totals as (
    select serial, count(*) as total, count(*) filter (where is_correct) as correct
    from latest group by serial
  )
  select coalesce(jsonb_agg(jsonb_build_object('serial',r.serial,'total',coalesce(t.total,0),'correct',coalesce(t.correct,0)) order by r.serial),'[]'::jsonb)
  into result from requested r left join totals t using (serial);
  return result;
end $$;

revoke all on function public.worker_answer_stats(text[]) from public, anon, authenticated;
grant execute on function public.worker_answer_stats(text[]) to service_role;

commit;
