-- 練習問題（AI生成）保存テーブル
-- Supabase SQL Editor で実行してください。

begin;

create table if not exists public.practice_questions (
  id bigint generated by default as identity primary key,
  base_serial text not null,
  focus text not null default '',
  stem text not null default '',
  choices jsonb not null default '[]'::jsonb,
  answer_index integer,
  explanation text not null default '',
  good_count bigint not null default 0,
  bad_count bigint not null default 0,
  model text not null default '',
  mode text not null default '' check (mode in ('', 'free', 'paid')),
  created_by uuid,
  created_at timestamptz not null default now()
);

create index if not exists practice_questions_base_serial_created_at_idx
  on public.practice_questions (base_serial, created_at desc);

create index if not exists practice_questions_votes_idx
  on public.practice_questions (good_count desc, bad_count desc, created_at desc);

alter table public.practice_questions enable row level security;

do $$
begin
  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'practice_questions'
      and policyname = 'practice_questions_read'
  ) then
    create policy practice_questions_read
      on public.practice_questions
      for select
      using (true);
  end if;
end $$;

commit;

