-- 練習問題（AI生成）保存テーブル
-- Supabase SQL Editor で実行してください。

begin;

create table if not exists public.practice_questions (
  id bigint generated by default as identity primary key,
  base_serial text not null,
  question_type text not null default 'mcq' check (question_type in ('mcq', 'tf', 'short')),
  focus text not null default '',
  stem text not null default '',
  choices jsonb not null default '[]'::jsonb,
  answer_index integer,
  answer_text text not null default '',
  explanation text not null default '',
  good_count bigint not null default 0,
  bad_count bigint not null default 0,
  model text not null default '',
  mode text not null default '' check (mode in ('', 'free', 'paid')),
  is_public boolean not null default true,
  published_at timestamptz,
  published_by uuid,
  created_by uuid,
  created_at timestamptz not null default now()
);

alter table public.practice_questions
  add column if not exists question_type text not null default 'mcq';

alter table public.practice_questions
  add column if not exists answer_text text not null default '';

update public.practice_questions
set question_type = 'mcq'
where question_type is null;

update public.practice_questions
set answer_text = ''
where answer_text is null;

alter table public.practice_questions
  alter column question_type set default 'mcq';

alter table public.practice_questions
  alter column question_type set not null;

alter table public.practice_questions
  alter column answer_text set default '';

alter table public.practice_questions
  alter column answer_text set not null;

alter table public.practice_questions
  add column if not exists is_public boolean not null default true;

alter table public.practice_questions
  add column if not exists published_at timestamptz;

alter table public.practice_questions
  add column if not exists published_by uuid;

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'practice_questions_question_type_check'
      and conrelid = 'public.practice_questions'::regclass
  ) then
    alter table public.practice_questions
      add constraint practice_questions_question_type_check
      check (question_type in ('mcq', 'tf', 'short'));
  end if;
end $$;

create index if not exists practice_questions_base_serial_created_at_idx
  on public.practice_questions (base_serial, created_at desc);

create index if not exists practice_questions_base_serial_public_created_at_idx
  on public.practice_questions (base_serial, is_public, created_at desc);

create index if not exists practice_questions_votes_idx
  on public.practice_questions (good_count desc, bad_count desc, created_at desc);

alter table public.practice_questions enable row level security;

do $$
begin
  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'practice_questions'
      and policyname = 'practice_questions_read'
  ) then
    create policy practice_questions_read
      on public.practice_questions
      for select
      using (true);
  end if;
end $$;

drop policy if exists practice_questions_read on public.practice_questions;

create policy practice_questions_read
  on public.practice_questions
  for select
  using (is_public = true or auth.uid() = created_by);

commit;
