-- 問題別・学習川柳（AI生成）保存テーブル
-- Supabase SQL Editor で実行してください。

begin;

create table if not exists public.question_senryu (
  id bigint generated by default as identity primary key,
  base_serial text not null,
  senryu text not null default '',
  commentary text not null default '',
  good_count bigint not null default 0,
  bad_count bigint not null default 0,
  model text not null default '',
  mode text not null default '' check (mode in ('', 'free', 'paid')),
  created_by uuid,
  created_at timestamptz not null default now()
);

alter table public.question_senryu
  add column if not exists senryu text not null default '';

alter table public.question_senryu
  add column if not exists commentary text not null default '';

alter table public.question_senryu
  add column if not exists good_count bigint not null default 0;

alter table public.question_senryu
  add column if not exists bad_count bigint not null default 0;

alter table public.question_senryu
  add column if not exists model text not null default '';

alter table public.question_senryu
  add column if not exists mode text not null default '';

update public.question_senryu
set senryu = ''
where senryu is null;

update public.question_senryu
set commentary = ''
where commentary is null;

update public.question_senryu
set good_count = 0
where good_count is null;

update public.question_senryu
set bad_count = 0
where bad_count is null;

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'question_senryu_mode_check'
      and conrelid = 'public.question_senryu'::regclass
  ) then
    alter table public.question_senryu
      add constraint question_senryu_mode_check
      check (mode in ('', 'free', 'paid'));
  end if;
end $$;

create index if not exists question_senryu_base_serial_created_at_idx
  on public.question_senryu (base_serial, created_at desc);

create index if not exists question_senryu_ranking_idx
  on public.question_senryu (good_count desc, bad_count asc, created_at desc);

create index if not exists question_senryu_created_at_idx
  on public.question_senryu (created_at desc);

alter table public.question_senryu enable row level security;

drop policy if exists question_senryu_read on public.question_senryu;

create policy question_senryu_read
  on public.question_senryu
  for select
  using (true);

commit;
