begin;

create table if not exists public.tag_deep_dive_explanations (
  tag text primary key,
  explanation text not null default '',
  model text not null default '',
  created_by uuid,
  updated_at timestamptz not null default now(),
  created_at timestamptz not null default now()
);

create index if not exists tag_deep_dive_explanations_updated_at_idx
  on public.tag_deep_dive_explanations (updated_at desc);

create table if not exists public.tag_qa (
  id bigint generated by default as identity primary key,
  tag text not null,
  status text not null check (status in ('ok', 'irrelevant')),
  question text not null default '',
  answer text not null default '',
  view_count bigint not null default 0,
  like_count bigint not null default 0,
  created_by uuid,
  created_at timestamptz not null default now()
);

create index if not exists tag_qa_tag_created_at_idx
  on public.tag_qa (tag, created_at desc);

create index if not exists tag_qa_tag_score_idx
  on public.tag_qa (tag, like_count desc, view_count desc, created_at desc);

alter table public.tag_deep_dive_explanations enable row level security;
alter table public.tag_qa enable row level security;

do $$
begin
  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'tag_deep_dive_explanations'
      and policyname = 'tag_deep_dive_explanations_read'
  ) then
    create policy tag_deep_dive_explanations_read
      on public.tag_deep_dive_explanations
      for select
      using (true);
  end if;
end $$;

do $$
begin
  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'tag_qa'
      and policyname = 'tag_qa_read'
  ) then
    create policy tag_qa_read
      on public.tag_qa
      for select
      using (true);
  end if;
end $$;

commit;
